<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>Andrew Camilleri</Authors>
    <PackageProjectUrl>https://github.com/Kukks/BlazorDashboardKit</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Kukks/BlazorDashboardKit</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
